name: deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.13'
    
    - name: Pull Mongo Docker
      run: |
            docker pull mongo

    - name: Test & Lint
      run: |
            go test -race -cover ./...
            go vet ./...
            test -z $(gofmt -s -l -w .)
      working-directory: ./api
      
    - name: Build
      run: |
            CGO_ENABLED=0 GOOS=linux go build -a -ldflags '-extldflags "-static"' -o ../main
      working-directory: ./api/server

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Function
      uses: Azure/functions-action@v1
      with:
        app-name: "order-test"
